---
- name: "install webapp v5"
  become: yes
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - files/secrets/credentials.yml
  tasks:
    - name: Create webapp directory
      file:
        path: webapp
        state: directory
    - name: Generate html
      template:
        src: templates/index.html.j2
        dest: "/home/{{ ansible_user }}/webapp/index.html"
    - name: "Launching an HTTPD Container"
      docker_container:
        name: apache-server
        image: httpd
        state: started
        ports: "{{ port }}:80"
        volumes:
          - /home/{{ ansible_user }}/webapp/:/usr/local/apache2/htdocs/:z
...
